module.exports = [
    {
        id: 1,
        users_id: 1,
        first_name: "Melanie",
        last_name: "Perkins",
        position: "CEO",
        email: "melanie@canva.com",
        image_url: "https://i.imgur.com/jBtjbSN.jpg",
        phone: "627572857",
        linked_in_url: "https://linkedin.com/melanieperkins",
        status: "In Progress",
    },
    {
        id: 2,
        users_id: 1,
        first_name: "Elon",
        last_name: "Musk",
        position: "CEO",
        email: "elon@tesla.com",
        image_url: "https://i.imgur.com/x3xiJfk.jpg",
        phone: "96572175",
        linked_in_url: "https://linkedin.com/melanieperkins",
        status: "CL Approved",
    },
    {
        id: 3,
        users_id: 2,
        first_name: "Mark",
        last_name: "Zuckerberg",
        position: "CEO",
        email: "mark@meta.com",
        image_url: "https://i.imgur.com/P7ahMdf.jpg",
        phone: "227275672",
        linked_in_url: "https://linkedin.com/melanieperkins",
        status: "Rejected",
    },
    {
        id: 4,
        users_id: 1,
        first_name: "Bill",
        last_name: "Gates",
        position: "Founder",
        email: "bill@microsoft.com",
        image_url: "https://i.imgur.com/y3IvBKS.jpg",
        phone: "678282589",
        linked_in_url: "https://linkedin.com/melanieperkins",
        status: "In Progress",
    },
    {
        id: 5,
        users_id: 1,
        first_name: "Melissa",
        last_name: "Benoist",
        position: "Producer",
        email: "melanie@warnerbrothers.com",
        image_url: "https://i.imgur.com/vzUZsDN.jpg",
        phone: "59724718",
        linked_in_url: "https://linkedin.com/melanieperkins",
        status: "Rejected",
    },
];
