module.exports = [
    {
        id: 1,
        first_name: "Timo",
        last_name: "Huennebeck",
        desired_position: "Software Developer",
        email: "hello@timohuennebeck.com",
        street_name: "5th Avenue, New York",
        postcode: "7282",
        google_url: "https://fakeurl.com",
    },
    {
        id: 2,
        first_name: "Brad",
        last_name: "Pitt",
        desired_position: "Actor",
        email: "bradpitt@gmail.com",
        street_name: "22nd Melbourne Street",
        postcode: "8592",
        google_url: "https://fakeurl.com",
    },
    {
        id: 3,
        first_name: "Dua",
        last_name: "Lipa",
        desired_position: "Singer",
        email: "dualipa@gmail.com",
        street_name: "11th LA Street",
        postcode: "7591",
        google_url: "https://fakeurl.com",
    },
    {
        id: 4,
        first_name: "The",
        last_name: "Rock",
        desired_position: "WWE Star",
        email: "therock@johnson.com",
        street_name: "2nd Nevada Road",
        postcode: "8591",
        google_url: "https://fakeurl.com",
    },
    {
        id: 5,
        first_name: "Tom",
        last_name: "Cruise",
        desired_position: "Tennis Pro",
        email: "tomcruise@gmail.com",
        street_name: "95th Windborn Road",
        postcode: "7858",
        google_url: "https://fakeurl.com",
    },
];
