module.exports = [
    {
        id: 1,
        first_name: "Timo",
        last_name: "Huennebeck",
        desired_position: "Software Developer",
        email: "hello@timohuennebeck.com",
        image_url: "https://i.imgur.com/2iIgpXm.jpg",
        street_name: "5th Avenue",
        city: "Melbourne",
        postcode: "3000",
        state: "VIC",
        country: "Australia",
        google_url: "https://fakeurl.com",
    },
    {
        id: 2,
        first_name: "Brad",
        last_name: "Pitt",
        desired_position: "Actor",
        email: "bradpitt@gmail.com",
        image_url: "https://i.imgur.com/W01EuAz.jpg",
        street_name: "11th Hallow Lane",
        city: "Medina",
        postcode: "6582",
        state: "Washington",
        country: "USA",
        google_url: "https://fakeurl.com",
    },
    {
        id: 3,
        first_name: "Dua",
        last_name: "Lipa",
        desired_position: "Singer",
        email: "dualipa@gmail.com",
        image_url: "https://i.imgur.com/VoqShKt.jpg",
        street_name: "11th LA Street",
        street_name: "2nd Newland Brow",
        city: "San Franscisco",
        postcode: "6582",
        state: "California",
        country: "USA",
        google_url: "https://fakeurl.com",
    },
    {
        id: 4,
        first_name: "The",
        last_name: "Rock",
        desired_position: "WWE Star",
        email: "therock@johnson.com",
        image_url: "https://i.imgur.com/IryY30I.jpg",
        street_name: "2nd Nevada Road",
        street_name: "5th Avenue, New York",
        street_name: "23rd Avenue",
        city: "Los Angeles",
        postcode: "6582",
        state: "California",
        country: "USA",
        google_url: "https://fakeurl.com",
    },
    {
        id: 5,
        first_name: "Tom",
        last_name: "Cruise",
        desired_position: "Tennis Pro",
        email: "tomcruise@gmail.com",
        image_url: "https://i.imgur.com/cY6YJB3.jpg",
        street_name: "22nd Padgett's Road",
        city: "Toronto",
        postcode: "6582",
        state: "Ontario",
        country: "Canada",
        google_url: "https://fakeurl.com",
    },
];
