module.exports = [
    {
        id: 1,
        first_name: "Dua",
        last_name: "Lipa",
        nickname: "dualipa",
        password: "JL:1590!germany:",
        desired_position: "Singer",
        email: "dualipa@gmail.com",
        image_url: "https://i.imgur.com/VoqShKt.jpg",
        street_name: "11th LA Street",
        street_name: "2nd Newland Brow",
        city: "San Franscisco",
        postcode: "6582",
        state: "California",
        country: "USA",
        google_url: "https://fakeurl.com",
    },
    {
        id: 2,
        first_name: "Tom",
        last_name: "Cruise",
        nickname: "tomcruise",
        password: "JL:1590!germany:",
        desired_position: "Tennis Pro",
        email: "tomcruise@gmail.com",
        image_url: "https://i.imgur.com/cY6YJB3.jpg",
        street_name: "22nd Padgett's Road",
        city: "Toronto",
        postcode: "6582",
        state: "Ontario",
        country: "Canada",
        google_url: "https://fakeurl.com",
    },
];
